### ISSUE TITLE
Suggest using renv

### ISSUE THREAD

**Issue by edward-burn** [ohdsi-studies/SvvEhden#2]
Instead of including a zip folder of cohort diagnostics within this repository, I would suggest using renv (https://rstudio.github.io/renv/articles/renv.html) instead to manage dependencies

**Comment by OskarGauffin** [comment]
Dear Ed,

As you suggested in your email, the binary zip-file for the custom version of CohortDiagnostics is not so much for dependency managment, as for adding features not available in the standard CohortDiagnostics package. One could probably use renv to install this particular version of CohortDiagnostics as well though, we'll see if this seems straightforward.

Overall, we think it's a great idea to use renv, especially if you start experiencing issues with different package versions. The reason why we've turned it off is that we've had some issues with it in the past during package development, trivial package updates force us into hour long updating of all dependency packages, and we haven't really had the time to dive into why this happens. But I think we could at least init a renv-file just before pushing the package to github.

**Comment by OskarGauffin** [comment]
Dear Ed,

We've now spent some time trying to make renv work, but it is simply not working out for us. It did seem to work for a while, but once we try to restore a nicely synced lockfile + library on a test computer, packages that are installed disappear, and Rstudio seems to become slow with renv activated, running "1+1" takes two minutes, if you deactivate renv it turns quick again. We can't really afford to spend more time on this right now, unfortunately.

**Comment by OskarGauffin** [comment]
As communicated in email, we have downprioritized the use of renv due to some bugs appearing when we run with renv activated.
