### ISSUE TITLE
CPRD error at install.packages

### ISSUE THREAD

**Issue by edward-burn** [ohdsi-studies/SvvEhden#3]
I am getting the error below when running this https://github.com/ohdsi-studies/SvvEhden/blob/8447fef45a07639b8fb725dd47131a7df2a70324/extras/RunCohortDiagnosticsAndViewResult.R#L57

```
> #pkgbuild::build(dest_path=path_to_project_root, binary=TRUE, args="--no-multiarch")
> tryCatch({
+   install.packages(repos=NULL, pkgs="../CohortDiagnostics_2.2.1.zip", INSTALL_opts="--no-multiarch", dependencies=TRUE)
+ })
Installing package into ‘/home/eburn/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0\xb0V\xdbT\0\0\0\0\0\0\0\0\0\0\0\0\022\0\0\0CohortDiagnostics/PK\003\004\n\0\0\0\0\0\xa9V\xdbT\0\0\0\0\0\0\0\0\0\0\0\0\032\0\0\0CohortDiagnostics/coho'
Warning in install.packages :
  installation of package ‘../CohortDiagnostics_2.2.1.zip’ had non-zero exit status
> library("CohortDiagnostics")
Error in library("CohortDiagnostics") : 
  there is no package called ‘CohortDiagnostics’
```

**Comment by OskarGauffin** [comment]
From the path, are you running this on linux? 

Perhaps you could try the pkgbuild-line and see if the package produced installs, instead of the binary we built (in Windows)?

**Comment by edward-burn** [comment]
Running the commented out line
https://github.com/ohdsi-studies/SvvEhden/blob/8447fef45a07639b8fb725dd47131a7df2a70324/extras/RunCohortDiagnosticsAndViewResult.R#L56

first led to this error: 
```
 pkgbuild::build(dest_path=path_to_project_root, binary=TRUE, args="--no-multiarch")
─  installing to library ‘/tmp/RtmpjZUper/temp_libpathf2efa69809ec5’
   ERROR: dependency ‘ROhdsiWebApi’ is not available for package ‘CohortDiagnostics’
```

But after installing ROhdsiWebApi, it seems to have worked. And then after running 
`install.packages("/home/eburn/SvvEhden-master/CohortDiagnostics_2.2.1_R_x86_64-pc-linux-gnu.tar.gz", repos = NULL, type="source")` I think I have it succesfully installed :) 

So I´ll close this issue, but hopefully the above is useful in case someone else has a similar set up

**Comment by OskarGauffin** [comment]
That's great, and thanks for trying!
